Traceback (most recent call last):
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 778, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 182, in ensure_async
    result = await obj
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\site-packages\jupyter_client\channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1001, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 802, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "C:\Users\claud\anaconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 852, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
windows=[7,14,21,28]
horizons=[7,14,21,28]
dropout_rates=[0.2,0.4,0.6,0.8]
batchsizes=[16,32,64,128]
neurons_list=[10, 100, 1000,10000]


datos=data['Price']
validation_metrics_price,test_metrics_price,train_metrics_price,residual_hist_price,best_model_price,params_best_model_price,residuals_bestmodel_price=busqueda (datos,windows,horizons,dropout_rates,batchsizes,neurons_list)
-------------------

